Updated example to use frontend/backend structure and renamed gateway app to frontend
aws/aws-app-mesh-examples pull request #373
Opened 2020-12-31 14:48 UTC by sshver

*Issue #, if available:*

*Description of changes:*

1. `gateway` in the walkthrough is an application that can’t be replicated with a Virtual Gateway. Renamed `gateway` app to `frontend` as used in other examples of the walkthrough.
  
Walkthrough and examples updated:
 - ColorApp
 - fargate
 - howto-cross-account
 - howto-servicediscovery-cloudmap
 - howto-timeout-policy
 - howto-tls-file-provided

2. AWS ECR CLI command `get-login` is deprecated in AWS CLI version 2. Replaced `get-login` to use `get-login-password` for CLI version 2.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-01-05 18:40 UTC, rajal-amzn requested changes
Instead of renaming the gateway to frontend, we would want to change the gateway task from an application with gateway image to do the forward to a Virtual Gateway.

2021-01-06 06:35 UTC, dfezzie commented on walkthroughs/howto-cross-account/primary-account/deploy.sh
> +    if [ $AWS_CLI_VERSION -gt 1 ]; then
Appreciate this change

2021-01-06 06:38 UTC, dfezzie commented
I agree with changing the names from `gateway` to `frontend` as it helps avoid confusion with the `gateway` feature. I agree with @rajal-amzn though and we should actually utilize the App Mesh `gateway` feature in these examples. I would start with one to get the approach down and then open separate PRs for the different walk throughs.

2021-02-25 00:33 UTC, sshver commented
Closing this pull request. Created separate PRs for each walkthrough.

2021-02-25 00:33 UTC, closed without merging