Feature/eks appmesh connectivity
aws/aws-app-mesh-examples pull request #401
Opened 2021-03-04 02:10 UTC by saleem-mirza

Create Kubernetes manifests for Yelb application
Add App Mesh support to Yelb application by Kubernetes CRD
Add recipepuppy end point to sample application
Add scripts to deploy Aurora PostgreSQL and ElastiCache dynamically

2021-03-08 14:34 UTC, buzzsurfr requested changes
Just need basic instructions on the README.

2021-03-08 14:34 UTC, buzzsurfr commented on blogs/eks-appmesh-connectivity/deployments/yaml/README.md
> +
Please add a few instructions on where to start (prerequisites) and the basic commands used to get this example running.

2021-03-12 03:36 UTC, buzzsurfr approved these changes

2021-03-12 03:36 UTC, merged

2021-03-12 14:17 UTC, mrichman commented on blogs/eks-appmesh-connectivity/deployments/infrastructure/setup-rds.sh
> +sleep 30s
Instead of sleep: https://docs.aws.amazon.com/cli/latest/reference/rds/wait/db-instance-available.html